=== {learning-goals}

// tag::DE[]

In diesem Teil lernen die Teilnehmer den Kern des methodischen Vorgehens zur qualitativen Bewertung von Software-Architekturen kennen.

[[LZ-3-1]]
==== LZ 3-1: ATAM – Architecture Tradeoff Analysis Method

* Bewertungsworkshops nach ATAM geeignet vorbereiten
* Die Phasen von ATAM erklären
* Die Schritte der Kernphasen von ATAM (Phase 1 und 2) erklären und auf die Bedürfnisse des eigenen Projekts anpassen.

[[LZ-3-2]]
==== LZ 3-2: Input für Workshops

* Anforderungen an Architekturdokumentation für Bewertungsworkshops verstehen und benennen:
* Detaillierte Szenarien
* Gesammelte Rahmenbedingungen
* Nachvollziehbar dokumentierte Entscheidungen
* Sichten zur Unterstützung des Überblicks bzw. Detaildiskussionen
* Source Code Teile
* Messergebnisse und erhobene Metriken
* Anforderungen an die Darreichungsform und Toolunterstützung
* Szenarien als architekturrelevant erkennen und entsprechende Kriterien benennen (Querschnittlichkeit der nötigen Entscheidungen, schwere Abbildbarkeit in Bestehendes, teure Umsetzung, etc.)

[[LZ-3-3]]
==== LZ 3-3: Workshops durchführen

Qualitative Bewertung von Software-Architekturen nach ATAM durchführen:
* Vorgehen bei qualitativer Bewertung erklären und durchführen
* Erstellung von Szenarien und Qualitätsbäumen erklären und durchführen
* Analyse von Software-Architekturen hinsichtlich Szenarien und Identifikation entsprechender Risiken selbständig durchführen.

[[LZ-3-4]]
==== LZ 3-4: Bewertung und Vorgehen

* Szenariobasierte Bewertungsmethoden in gängige Vorgehensmodelle einbetten
* Iterative Entwicklung
* Agile Vorgehensweisen
* In all diesen Vorgehensmodellen: das Zusammenspiel mit der Umsetzung verstehen und erklären.

[[LZ-3-5]]
==== LZ 3-5: Was sollen die Teilnehmer verstehen?

* Architekturbewertung ist als Teil des Entwicklungsprozesses (wiederkehrend) effektiver als ein Qualitätscheck vorhandener Software (nach erfolgter Implementierung).
* Die breite Beteiligung verschiedener Stakeholder ist wichtig für den Erfolg von Bewertungsworkshops.
* Bewertungsworkshops und die szenariobasierte Methodik verbessern die Kommunikation im Projekt und die Transparenz gegenüber Umsetzern und Kunden.
* CBAM ist eine ergänzende Methodik, die bei Kompromissen eingesetzt werden kann. Nutzenkurven helfen beim fällen schwieriger Entscheidungen.
* Quantitative Techniken können zur Unterstützung von szenariobasierten Bewertungen eingesetzt werden.
* Die Einführung von Bewertungsworkshops im eigenen Projekt oder Unternehmen muss geplantwerden und schrittweise erfolgen.

[[LZ-3-6]]
==== LZ 3-5: Was sollen die Teilnehmer kennen?

Unterschiede in der Durchführung von Bewertungsworkshops mit unterschiedlichen Teilnehmergruppen (interne und externe Stakeholder).
Unterschiede verschiedener szenariobasierter Methoden bei der Bewertung selbst (SAAM, ATAM, CBAM, LAAAM).

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: TBD
tbd.

[[LG-3-2]]
==== LG 3-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
