=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Grundlagen der Softwarearchitektur verstehen

* Begründen, warum Architekturarbeit grundlegend ist, im Projekt breite Auswirkungen hat und entsprechende Entscheidungen schwer zurückzunehmen sind
* Begründen, warum Architekturarbeit iterativ erfolgen sollte und Feedbackschleifen benötigt
* Begründen, dass der Fokus von Softwarearchitektur auf Qualitätsmerkmalen liegt als Differenzierung gegenüber reiner Funktionalität
* Verstehen die Notwendigkeit von Gruppenprozessen für die Weiterentwicklung von Softwarearchitekturen

[[LZ-1-2]]
==== LZ 1-2: Nutzen von Architekturbewertung erklären

* (Frühe) Erkennung von zentralen Risiken und Problemen bezüglich der geforderten Qualitätsmerkmale
* Methodische Absicherung von Architekturentscheidungen – Sicherung der langfristigen Nachvollziehbarkeit der Architektur
* Qualifiziertes Feedback zu Architekturentscheidungen
* Generelle Förderung von Kommunikation und Transparenz
** Verlorenes Vertrauen von Stakeholdern kann rückgewonnen werden
** Widersprüche in Anforderungen werden aufgedeckt
** Einordnung und Gewichtung von technischen und konzeptionellen Stärken und Schwächen
* Förderung methodischer Architekturentwicklung und sauberer Architekturdokumentation

[[LZ-1-3]]
==== LZ 1-3: Anlässe zur Architekturbewertung benennen

* methodische Gründe (als üblicher Teil des Architekturprozesses, ...)
* organisatorische Gründe (Strategieentscheidungen, Investitionen, ...)
* technische Gründe (Technologiewechsel, Ablösungen, ...)
* Unsicherheit (mangelnder Überblick, Betriebsblindheit, ...)

[[LZ-1-4]]
==== LZ 1-4: Voraussetzungen für Architekturbewertung erläutern

* Notwendige Artefakte der Softwarearchitektur und deren angemessenen Detaillierungsgrad in konkreten Projektsituationen 
* Rahmenbedingungen
* Konkrete Qualitätsanforderungen
* Dokumentierte Architekturentscheidungen
* Architekturüberblick
* Kooperationsbereitschaft der Stakeholder
* Bereitschaft der Organisation, Budget und Zeit für den Bewertungsprozess bereitzustellen

[[LZ-1-5]]
==== LZ 1-5: Verschiedene Methoden und Ansätze zur Architekturbewertung voneinander unterscheiden

* Szenarienbasierte Bewertungsmethoden (ATAM, Lightweight ATAM, CBAM, ...)
* Entscheidungsbasierte Verfahren (DCAR, PBAR, ...)
* Expertenreviews (TARA, informell, ...)
* quantitativ, messende Techniken
* Konformitätsanalysen (Architektur, Code)

[[LZ-1-6]]
==== LZ 1-6: Verstehen, dass verschiedene Methoden einander ergänzen und kombiniert werden können

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understand the basics of software architecture

* Reason why architectural work is fundamental, how it has broad implications in the project, and that architecture decisions are difficult to revoke
* Reason why architecture work should be iterative and needs feedback loops
* Reason that the focus of software architecture is on quality attributes and not just pure functionality.
* Understand the necessity of group processes for the further development of software architectures

[[LG-1-2]]
==== LG 1-2: Explain the benefits of architecture evaluation

* (Early) identification of key risks and problems with regard to the required quality attributes
* Methodical safeguarding of architecture decisions - ensuring the long-term traceability of the architecture.
* Qualified feedback on architecture decisions
* General promotion of communication and transparency
** Lost trust of stakeholders can be regained
** Contradictions in requirements are uncovered
** Classification and weighting of technical and conceptual strengths and weaknesses
* Promotion of methodical architecture development and clean architecture documentation

[[LG-1-3]]
==== LG 1-3: Name motives for for architecture evaluation

* Methodological reasons (as a usual part of the architecture process, ...)
* Organizational reasons (strategic decisions, investments, ...)
* Technical reasons (changes of technology, replacements, ...)
* Uncertainty (lack of overview, operational blindness, ...)

[[LG-1-4]]
==== LG 1-4: Explain prerequisites for architecture evaluation

* Necessary artifacts of software architecture and their appropriate level of detail in concrete project situations. 
* Constraints
* Concrete quality requirements
* Documented architecture decisions
* Architecture overview
* Stakeholder willingness to cooperate
* Willingness of the organization to allocate budget and time to the evaluation process

[[LG-1-5]]
==== LG 1-5: Differentiate various methods and approaches to architecture evaluation

* Scenario-based evaluation methods (ATAM, Lightweight ATAM, CBAM, ...).
* Decision-based methods (DCAR, PBAR, ...)
* Expert reviews (TARA, informal, ...)
* Quantitative, measuring techniques
* Conformance analyses (architecture, code)

[[LG-1-6]]
==== LG 1-6: Understand that different methods complement each other and can be combined
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
