=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Nutzen und Ziele von Software-Architektur

* Begründen, warum Architekturarbeit grundlegend ist, im Projekt breite Auswirkungen hat und entsprechende Entscheidungen schwer zurückzunehmen sind
* Begründen, warum Architekturarbeit iterativ erfolgen sollte und Feedbackschleifen benötigt
* Begründen, dass der Fokus von Software-Architektur auf Qualitätsmerkmalen liegt als Differenzierung gegenüber reiner Funktionalität
* Verstehen die Notwendigkeit von Gruppenprozessen für die Weiterentwicklung von Software-Architekturen

[[LZ-1-2]]
==== LZ 1-2: Nutzen und Ziele von Architekturbewertung

Nutzen von Architekturbewertung erklären:

* (Frühe) Erkennung von zentralen Risiken und Problemen bezüglich der geforderten Qualitätsmerkmale
* Methodische Absicherung von Architekturentscheidungen – Sicherung der langfristigen Nachvollziehbarkeit der Architektur
* Qualifiziertes Feedback zu Architekturentscheidungen
* Generelle Förderung von Kommunikation und Transparenz
** Verlorenes Vertrauen von Stakeholdern kann rückgewonnen werden
** Widersprüche in Anforderungen werden aufgedeckt
** Einordnung und Gewichtung von technischen und konzeptionellen Stärken und Schwächen
* Förderung methodischer Architekturentwicklung und sauberer Architekturdokumentation

Anlässe zur Architekturbewertung benennen:

* methodische Gründe (als üblicher Teil des Architekturprozesses, ...)
* organisatorische Gründe (Strategieentscheidungen, Investitionen, ...)
* technische Gründe (Technologiewechsel, Ablösungen, ...)
* Unsicherheit (mangelnder Überblick, Betriebsblindheit, ...)

[[LZ-1-3]]
==== LZ 1-3: Voraussetzungen für Architekturbewertung

Organisatorische, technische und weiche Voraussetzungen erläutern:

* Notwendige Artefakte der Software-Architektur und deren angemessenen Detaillierungsgrad in konkreten Projektsituationen 
* Rahmenbedingungen
* Konkrete Qualitätsanforderungen
* Dokumentierte Architekturentscheidungen
* Architekturüberblick
* Kooperationsbereitschaft der Stakeholder
* Bereitschaft der Organisation, Budget und Zeit für den Bewertungsprozess bereitzustellen

[[LZ-1-4]]
==== LZ 1-4: Architekturbewertungsmethoden

Verschiedene Methoden und Ansätze zur Architekturbewertung voneinander unterscheiden:

* Szenarienbasierte Bewertungsmethoden (ATAM, Lightweight ATAM, CBAM, ...)
* Entscheidungsbasierte Verfahren (DCAR, PBAR, ...)
* Expertenreviews (TARA, informell, ...)
* quantitativ, messende Techniken
* Konformitätsanalysen (Architektur, Code)

Verstehen, dass verschieden Methoden einander ergänzen und kombiniert werden können.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: The is the first learning goal, in category xy
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
