=== {learning-goals}

// tag::DE[]

Vorstellung, eventuell Erarbeitung und Bewertung mindestens eines Beispiels einer Softwarearchitektur.

[[LZ-98-1]]
==== LZ 98-1: Was sollen die Teilnehmer verstehen?

Den Ablauf von Bewertungsworkshops und die Bewertungsmöglichkeiten die sich bei realitätsnahen
Architekturen ergeben.

[[LZ-98-2]]
==== LZ 98-2: Was sollen die Teilnehmer kennen?

Einige Beispiele (möglichst) realitätsnaher Bewertungsinputs und Bewertungsergebnisse:

* Szenarien
* Dokumentierte Rahmenbedingungen
* Dokumentierte Entscheidungen
* Architekturüberblick
* Pain Points und sensitive Punkte
* Dokumentierte Kompromisse, Risiken und Nicht-Risiken

// end::DE[]


// tag::EN[]
Presentation, possibly elaboration and evaluation of at least one example of a software architecture.

[[LG-98-1]]
==== LG 98-1: What do participants need to understand?

The process of evaluation workshops and the evaluation possibilities that arise with realistic
architectures.

[[LG-98-2]]
==== LG 98-2: What do participants need to know?

Some examples of (as close as possible) realistic evaluation inputs and evaluation results:

* Scenarios
* Documented constraints
* Documented decisions
* Architecture overview
* Pain points and sensitive points
* Documented trade-offs, risks and non-risks
// end::EN[]

