=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Qualitative Anforderungen untersuchen und behandeln

Die Bedeutung von qualitativen Anforderungen für die Architektur erklären. 

#TODO: Duplikat zu 1-3. löschen/verschieben? Verstehen dass konkrete und detaillierte Benennung der treibenden Qualitätsanforderungen die Voraussetzung für gute Architekturarbeit und Architekturbewertung ist

Die Begriffe "Qualität" und "Qualitätsmerkmal" präzisieren.

Verschiedene Qualitätsmodelle (z.B. DIN/ISO 25010) interpretieren.

Eigenschaften wichtiger Qualitätsmerkmale erklären:

  * Grundlegende Herangehensweise zur Behandlung
  * Zusammenhang und Wechselwirkungen von Qualitätsmerkmalen.

[[LZ-2-2]]
==== LZ 2-2: Qualitätsanforderungen detaillieren und beschreiben

Arten von Szenarien voneinander unterscheiden:
  
  * Use-Case-Szenarien
  * Grenzszenarien
  * Stressszenarien

Erhebungstechniken für Szenarien anwenden:

  * Brainstorming / Quality Storming
  * Interview
  * Ableitung aus NFR-Spezifikation

Mögliche Bestandteile von Szenarien zur Verfeinerung und Konkretisierung erklären.

Unterbringung von Szenarien in Architekturdokumentation beschreiben.

Arbeiten mit Qualitätsbäume:

  * Deren Nutzen erklären
  * Eigene Qualitätsbäume erstellen
  * Zur Priorisierung von Qualitätsanforderungen verwenden

[[LZ-2-3]]
==== LZ 2-3: Architektursichten

#TODO: können?

Architektursichten bedarfsgerecht für die Bewertung auswählen können:

  * Kontextsicht
  * Bausteinsicht
  * Laufzeitsicht
  * Verteilungssicht

#TODO: können?
Qualität der Sichten bewerten können.

Bedeutung der Sichten im Verlauf der verschiedenen Bewertungsmethoden erklären.

[[LZ-2-4]]
==== LZ 2-4: Architekturansätze und -entscheidungen 

Unterschiedliche Wirkungen der Begriffe Ansatz und Entscheidung erläutern.

Geeignete Formen der Entscheidungsdokumentation für die Bewertung auswählen:

  * ADRs
  * Stichpunkte
  * Konzepte
  * Source-Code-Teile
  * Messergebnisse und erhobene Metriken

[[LZ-2-5]]
==== LZ 2-5: Randbedingungen

Typische KAtegorien von Rahmenbedingungen kennen:

  * Technische Randbedingungen
  * Organisatorische Randbedingungen
  * Konventionen

Unterschiede zwischen Randbedingungen und Qualitätsanforderungen erklären:

  * Randbedingungen werden erfüllt oder nicht (binär)
  * Qualitätsanforderungen können teilweise oder auch übererfüllt werden

// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: TBD
tbd.

[[LG-2-2]]
==== LG 2-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
