=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Entscheidungsbasierte Bewertung

Entscheidungsbasierte Bewertung für bestehende Systeme:

* Unterschiede zur Bewertung von Konzepten und Ideen
* Unterschiede zur Umsetzungsüberprüfung mit Metriken und Messungen erklären

[[LZ-5-2]]
==== LZ 5-2: Umsetzungsprüfung

Umsetzungsprüfung auf Basis von Messungen und Bewertungstools:
* Bewertung von Software-Architekturen im Hinblick auf ihre Umsetzung durchführen, d. h. die Frage beantworten, in wie weit eine Architektur auch im Code umgesetzt wurde.
* Tools für den Abgleich von Umsetzung und Architekturidee benennen (Sonargraph, Structure101, ArchUnit etc.)
* Operationalisierung entsprechender Überprüfungen im Prozess integrieren (beispielsweise als Teil des Check-In-Vorgangs, im Build etc.).
* Verletzungen der Architekturvorgaben in der Implementierung behandeln

[[LZ-5-3]]
==== LZ 5-3: Statische Prüfung

Konkrete Metriken für die Überprüfung von Design Best-Practices erklären. Etwa Abstraktion, Instabilität, Distanz, Fan-In/Fan-Out, zyklomatische Komplexität.

Einsatz von Metriken planen (aus Zielsicht, nicht aus Toolsicht)

Bewertung von Software-Architekturen im Hinblick auf allgemeine Best-Practices oder Prinzipien durchführen:
* Bekannte Fehler im Quellcode und Fehlercluster analysieren
* Unterstützende Tools und Metriken anwenden
* Operationalisierung entsprechender Überprüfungen im Prozess integrieren (beispielsweise als Teil des Check-In-Vorgangs, im Build etc.).

[[LZ-5-4]]
==== LZ 5-4: Dynamische Prüfung

Möglichkeiten der dynamischen Software-Prüfung benennen und für dynamische Prüfung geeignete Qualitätsmerkmale kennen.

Ansätze der statischen Analyse in stark verteilten Umfeldern (Microservices) mit dynmaischen Mitteln nachstellen.

Einflächtung dieser Techniken in größere Bewertungsvorhaben erklären.

// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: TBD
tbd.

[[LG-5-2]]
==== LG 5-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
