=== {learning-goals}

// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Bewertung bestehender System(teil)e

* Unterschiede zur Bewertung von Konzepten und Ideen benennen
* Aktuelle Werkzeuge zur Unterstützung kennen und nach Einsatzzweck kategorisieren.
* Operationalisierung entsprechender Überprüfungen im Prozess integrieren (beispielsweise als Teil des Check-In-Vorgangs, im Build etc.).

[[LZ-5-2]]
==== LZ 5-2: Umsetzungsprüfung 

#TODO: meh
Source Codes gegen strukturelle Architekturansätze prüfen:

  * Bewertung von Software-Architekturen im Hinblick auf ihre Umsetzung durchführen, d. h. die Frage beantworten, in wie weit eine Architektur auch im Code umgesetzt wurde.
  * Tools für den Abgleich von Umsetzung und Architekturidee benennen (z.B. Sonargraph, Structure101, ArchUnit)
  * Eignung der Tools um Ist-Architekuren Bottom-Up zu erheben und Abgleiche mit Soll-Architekturen durchzuführen

[[LZ-5-3]]
==== LZ 5-3: Statische Prüfung


Konkrete Metriken für die Überprüfung von Design Best-Practices erklären. (z.B. Distanz, Fan-In/Fan-Out, zyklomatische Komplexität)

#TODO: wirklich planen?
Einsatz von Metriken planen (aus Zielsicht, nicht aus Toolsicht)

Messungen interpretieren (Default-Einstellungen hinterfragen, auf Trends achten) 

Verstehen, dass Messungen geeignete Ausgangspunkte für tiefere Analysen sind

[[LZ-5-4]]
==== LZ 5-4: Dynamische Prüfung

Möglichkeiten der dynamischen Software-Prüfung benennen und für dynamische Prüfung geeignete Qualitätsmerkmale kennen.

Ansätze der statischen Analyse in stark verteilten Umfeldern (Microservices) mit dynamischen Mitteln nachstellen.

Einflechtung dieser Techniken in größere Bewertungsvorhaben erklären.

// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: TBD
tbd.

[[LG-5-2]]
==== LG 5-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
