=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Bestehende System(teil)e bewerten können

* Unterschiede zur Bewertung von Konzepten und Ideen benennen
* Aktuelle Werkzeuge zur Unterstützung kennen und nach Einsatzzweck kategorisieren.
* Messungen und dynamische Prüfungen im Entwicklungsprozess verankern (beispielsweise als Teil des Check-In-Vorgangs, im Build etc.).

[[LZ-4-2]]
==== LZ 4-2: Umsetzungsprüfung der Architekturansätze im Source Code verstehen

* Bewertung von Softwarearchitekturen im Hinblick auf ihre Umsetzung durchführen, d. h. die Frage beantworten, in wie weit eine Architektur auch im Code umgesetzt wurde.
* Tools für den Abgleich von Umsetzung und Architekturidee benennen (z.B. Sonargraph, Structure101, ArchUnit)
* Eignung der Tools, um Ist-Architekuren Bottom-Up zu erheben und Abgleiche mit Soll-Architekturen durchzuführen, verstehen

[[LZ-4-3]]
==== LZ 4-3: Metriken zur Bewertung einsetzen 

* Konkrete Metriken für die Überprüfung von Design Best-Practices erklären. (z.B. Distanz, Fan-In/Fan-Out, zyklomatische Komplexität)
* Einsatz von Metriken planen (aus Zielsicht, nicht aus Toolsicht)
* Messungen interpretieren (Default-Einstellungen hinterfragen, auf Trends achten) 
* Verstehen, dass Messungen geeignete Ausgangspunkte für tiefere Analysen sind

[[LZ-4-4]]
==== LZ 4-4: Den Einsatz dynamischer Prüfverfahren planen

* Möglichkeiten der dynamischen Software-Prüfung benennen 
* Für dynamische Prüfung geeignete Qualitätsmerkmale kennen.
* Ansätze der statischen Analyse in stark verteilten Umfeldern (Microservices) mit dynamischen Mitteln nachstellen.
* Einflechtung dieser Techniken in größere Bewertungsvorhaben erklären.

// end::DE[]

// tag::EN[]

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
