=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Bestehende System(teil)e bewerten können

* Unterschiede zur Bewertung von Konzepten und Ideen benennen
* Aktuelle Werkzeuge zur Unterstützung kennen und nach Einsatzzweck kategorisieren.
* Messungen und dynamische Prüfungen im Entwicklungsprozess verankern (beispielsweise als Teil des Check-In-Vorgangs, im Build etc.).

[[LZ-4-2]]
==== LZ 4-2: Umsetzungsprüfung der Architekturansätze im Source Code verstehen

* Bewertung von Softwarearchitekturen im Hinblick auf ihre Umsetzung durchführen, d. h. die Frage beantworten, in wie weit eine Architektur auch im Code umgesetzt wurde.
* Tools für den Abgleich von Umsetzung und Architekturidee benennen (z.B. Sonargraph, Structure101, ArchUnit)
* Eignung der Tools, um Ist-Architekuren Bottom-Up zu erheben und Abgleiche mit Soll-Architekturen durchzuführen, verstehen

[[LZ-4-3]]
==== LZ 4-3: Metriken zur Bewertung einsetzen

* Konkrete Metriken für die Überprüfung von Design Best-Practices erklären. (z.B. Distanz, Fan-In/Fan-Out, zyklomatische Komplexität)
* Einsatz von Metriken planen (aus Zielsicht, nicht aus Toolsicht)
* Messungen interpretieren (Default-Einstellungen hinterfragen, auf Trends achten)
* Verstehen, dass Messungen geeignete Ausgangspunkte für tiefere Analysen sind

[[LZ-4-4]]
==== LZ 4-4: Den Einsatz dynamischer Prüfverfahren planen

* Möglichkeiten der dynamischen Software-Prüfung benennen
* Für dynamische Prüfung geeignete Qualitätsmerkmale kennen.
* Ansätze der statischen Analyse in stark verteilten Umfeldern (Microservices) mit dynamischen Mitteln nachstellen.
* Einflechtung dieser Techniken in größere Bewertungsvorhaben erklären.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Be able to evaluate existing system (or parts thereof)

* Name differences from the evaluation of concepts and ideas.
* Know current software tools and categorize them by purpose.
* Emed measurements and dynamic checks in the development process (for example, as part of the check-in process, in the build, etc.).

[[LG-4-2]]
==== LG 4-2: Understand how to evaluate the implementation of architectural approaches

* Evaluate software architectures with regard to their implementation, i.e. answer the question to what extent an architecture has also been implemented in the code.
* Name tools for the comparison of implementation and architecture ideas (e.g. Sonargraph, Structure101, ArchUnit).
* Assess the suitability of the tools for collecting bottom-up as-is architectures and performing comparisons with target architectures.

[[LG-4-3]]
==== LG 4-3: Use metrics for evaluation

* Explain metrics for reviewing design best practices. (e.g., distance, fan-in/fan-out, cyclomatic complexity).
* Plan use of metrics (to fulfill requirements, not for the sake of using a tool).
* Interpret measurements (question default settings, look for trends).
* Understand that measurements are appropriate starting points for deeper analysis.

[[LG-4-4]]
==== LG 4-4: Plan the use of dynamic analysis methods

* Name the potentials of dynamic software analysis.
* Know quality attributes suitable for dynamic analysis.
* Recreate approaches to static analysis in highly distributed environments (microservices) using dynamic means.
* Explain incorporation of these techniques into larger evaluation projects.

// end::EN[]


