// tag::DE[]
|===
| Dauer: 60 Min. | Übungszeit: 90 Min.
|===

=== Begriffe und Konzepte
ATAM, Kompromisse, Risiken, Nicht-Risiken, Sensitive Punkte, Entscheidungen, Rahmenbedingungen, Phasen von ATAM, Stakeholder-Beteiligung, szenariobasierte Durchsprache, Bewertungsworkshop, Discovery Review, Zusammenspiel mit der Entwicklung,Risikocluster, Minderungsmaßnahmen, Kommunikation der Ergebnisse, Reports, Präsentationen, Stärken und Schwächen, Ampel-Scores.

// end::DE[]

// tag::EN[]
|===
| Lesson duration: 60 min | Exercises: approx. 90 min
|===

=== Terms and Concepts
ATAM, trade-offs, risks, non-risks, sensitive points, decisions, framework, phases of ATAM, stakeholder participation, scenario-based walk-through, assessment workshop, discovery review, interacting with development,risk clusters, mitigation measures, communicating results, reports, presentations, strengths and weaknesses, traffic light scores.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Überschrift in 00-structure.adoc ersetzen
====
// end::REMARK[]

// tag::REMARK[]
[NOTE]
====
Sinnvolle Zeiten für Dauer und Übungszeit eintragen, vernünftige Begriffe aufzählen.
====
// end::REMARK[]
