=== {learning-goals}

// tag::DE[]

In diesem Teil lernen die Teilnehmer den Kern des methodischen Vorgehens zur qualitativen Bewertung von Software-Architekturen kennen.

[[LZ-3-1]]
==== LZ 3-1: ATAM – Architecture Tradeoff Analysis Method

* Bewertungsworkshops nach ATAM geeignet vorbereiten können
* Die Phasen von ATAM erklären
* Die Schritte der Kernphasen von ATAM (Phase 1 und 2) erklären und auf die Bedürfnisse des eigenen Projekts anpassen
* Beteiligte der einzelnen Phasen benennen
* Inputs für ATAM Workshops kennen und den Schritten zuordnen

[[LZ-3-2]]
==== LZ 3-2: Workshops durchführen

Qualitative Bewertung von Software-Architekturen nach ATAM durchführen:
  
  * Vorgehen bei qualitativer Bewertung erklären und durchführen
  * Erstellung von Szenarien und Qualitätsbäumen erklären und durchführen
  * Ansätze hinsichtlich Szenarien analysieren
  * Fragetechniken anwenden können, um die Analyse in Breite oder Tiefe zu lenken und den Fokus zu behalten
  * Risiken, Nicht-Risiken, Sensible Punkte und Kompromisse identifizieren und verständlich festhalten können
  * Bedeutung von Moderation begründen

[[LZ-3-3]]
==== LZ 3-3: Umgang mit Bewertungsergebnissen

Direkte und verdichtete Ergebnistypen ableiten:

  * Risikoclsuter und Risikogruppen
  * Stärken und Schwächen einer Architektur
  * Lücken zu den zentralen Qualitätszielen 

Kommunikationsmittel für die Vermittlung von Ergebnissen beschreiben:

  * Gegliederte Reports und deren wichtige Teile
  * Strukturierte Ergebnispräsentationen
  * Empfehlungen und deren Einsortierung in Lücken und Potentiale

#TODO: OK so?
Einflüsse der Ergebnisse auf iterative Prozesse verstehen: 
  
  * Risiken aktiv angehen
  * offene Entscheidungen planen
  * Unsicherheiten ausräumen

[[LZ-3-4]]
==== LZ 3-4: Bewertungsprozess an den eigenen Kontext anpassen

#TODO: wirklich können?
* Bewertungen nach Größe skalieren und Methoden bedarfsgerecht auswählen und anpassen können
* Quantitative Techniken zur Unterstützung von szenariobasierten Bewertungen einsetzen können
* Methoden zur Verschlankung des Verfahrens anwenden können (z.B. light weight ATAM)

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: TBD
tbd.

[[LG-3-2]]
==== LG 3-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
