=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Was sollen die Teilnehmer können?

* Die Ergebnisse von Bewertungsworkshops erarbeiten, dokumentieren und erklären:
* Risiken
* Nicht-Risiken
* Kompromisse
* Sensitive Punkte
* Allgemeine ToDos
* Ergebnisse von Bewertungsorkshops entsprechend verwerten und verfolgen
* Kommunikationsmittel für die Vermittlung von Ergebnissen kennen und nutzen.

[[LZ-4-2]]
==== LZ 4-2: Was sollen die Teilnehmer verstehen?

Risiken müssen aktiv angegangen werden.
Noch offene Entscheidungen müssen geplant werden.

[[LZ-4-3]]
==== LZ 4-3: Was sollen die Teilnehmer kennen?

Methoden zur Risikoeinschätzung und -behandlung.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: TBD
tbd.

[[LG-4-2]]
==== LG 4-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
