=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Ergebnistypen von Bewertungen

Die direkten Ergebnisse von Bewertungen erarbeiten, dokumentieren und erklären:
* Risiken
* Nicht-Risiken
* Kompromisse
* Sensitive Punkte
* Allgemeine ToDos

Abgeleitete und verdichtete Ergebnistypen benennen und herstellen können:
* Risikoclsuter und Risikogruppen
* Stärken und Schwächen einer Architektur
* Lücken zu den zentralen Qualitätszielen 
* Empfehlungen und deren Einsortierung in Lücken und Potentiale

[[LZ-4-2]]
==== LZ 4-2: Ergebnisformen und deren Herstellung

Kommunikationsmittel für die Vermittlung von Ergebnissen kennen und nutzen:
* Reports gliedern und wichtige Teile benennen
* Ergebnispräsentationen strukturieren
* Iterative Prozesse mit Ergebnissen befeuern - Risiken aktiv angehen, offene Entscheidungen planen, Unsicherheiten ausräumen, ...

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: TBD
tbd.

[[LG-4-2]]
==== LG 4-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
