// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlagen der Beschreibung von Architekturen mit Hilfe verschiedener Sichten, übergreifender Konzepte, Entwurfsentscheidungen, Randbedingungen etc., wie es im CPSA-Foundation Level vermittelt wird.
- Wünschenswert sind eigene Erfahrungen in der Erstellung und Pflege von Software, insbesondere der Architektur von Software- oder Software-nahen Systemen.

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Kenntnis typischer Herausforderungen beim Entwurf von Softwarearchitekturen:
  * Auswahl geeigneter Dokumentationsstrukturen, Notationen, Ergebnistypen (Stakeholderorientierung)
  * Gemeinsame Arbeit an grundlegenden Konzepten der zu erstellenden Software
  * Orientierung von Softwarearchitektur an Anforderungen und Rahmenbedingungen
  * Messung und Evaluation der Qualität von Entwürfen und Entscheidungen
// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Fundamentals of documenting software architectures using different views, cross-cutting concepts, design decisions, constraints, etc., as taught in CPSA Foundation Level.
- Desirable is own experience in the development and maintenance of software, especially the architecture of software or software-related systems.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Knowledge of typical challenges in the design of software architectures:
  * Selection of appropriate documentation structures, notations, result types (stakeholder orientation).
  * Joint work on fundamental concepts of the software to be created
  * Alignment of software architecture with requirements and constraints
  * Measuring and evaluating the quality of designs and decisions
// end::EN[]
