// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlagen der Beschreibung von Architekturen mit Hilfe verschiedener Sichten, übergreifender Konzepte, Entwurfsentscheidungen, Randbedingungen etc., wie es im CPSAF Foundation Level vermittelt wird.
- Wünschenswert sind eigene Erfahrungen in der Erstellung und Pflege von Software, insbesondere der Architektur von Software- oder Software-nahen Systemen.

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Kenntnis typischer Herausforderungen beim Entwurf von Software-Architekturen:
  * Auswahl geeigneter Dokumentationsstrukturen, Notationen, Ergebnistypen (Stakeholderorientierung)
  * Gemeinsame Arbeit an grundlegenden Konzepten der zu erstellenden Software
  * Orientierung von Software-Architektur an Anforderungen und Rahmenbedingungen
  * Messung und Evaluation der Qualität von Entwürfen und Entscheidungen
// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Kenntnisgruppen sowie Voraussetzungen bitte entsprechend ausformulieren!
====
// end::REMARK[]
